### PR TITLE
update README.md (miniforge, docker compose down)

### PR DESCRIPTION
**Pull request by rc**
Hi @BubuLK, is this the correct way to remove an old container?

### CODE REVIEW

**Comment by BubuLK** [comment]
Updated `README.md` in your PR was obsolete, sorry ;(
Docs updated and proposed changes are reflected in up-tu-date `sfepy-desktop/README.md`.

Thank you,
LK

**Comment by rc** [comment]
OK, makes sense to have only a single README. Can you mention there also the `docker compose down` command that I keep forgetting? :)

**Comment by BubuLK** [comment]
Should be already there...

**Comment by rc** [comment]
Yes, thank you!

**Pull request closed without merging**
